// <auto-generated />
using System;
using DawsonDial.Models.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DawsonDial.Migrations
{
    [DbContext(typeof(DawsonDialContext))]
    [Migration("20250506162945_AddScheduleIdToOfficeHours")]
    partial class AddScheduleIdToOfficeHours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DawsonDial.Models.Events.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConferenceRoomRoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("ConferenceRoomRoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("Events");

                    b.HasDiscriminator().HasValue("Event");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Section", b =>
                {
                    b.Property<Guid>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TeacherPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("SectionId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TeacherPersonId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.SectionRoom", b =>
                {
                    b.Property<Guid>("SectionRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uuid");

                    b.HasKey("SectionRoomId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionRooms");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.TimeSlot", b =>
                {
                    b.Property<Guid>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("TimeSlotId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("DawsonDial.Models.People.AdminLog", b =>
                {
                    b.Property<Guid>("AdminLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AdminLogId");

                    b.HasIndex("AdminId");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonId");

                    b.ToTable("People");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.Room", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("integer");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasDiscriminator().HasValue("Room");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EventPerson", b =>
                {
                    b.Property<Guid>("EventsEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantsPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("EventsEventId", "ParticipantsPersonId");

                    b.HasIndex("ParticipantsPersonId");

                    b.ToTable("EventPerson");
                });

            modelBuilder.Entity("SectionStudent", b =>
                {
                    b.Property<Guid>("ClassesSectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnrolledStudentsPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassesSectionId", "EnrolledStudentsPersonId");

                    b.HasIndex("EnrolledStudentsPersonId");

                    b.ToTable("SectionStudent");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.ClassSession", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Events.Event");

                    b.Property<Guid?>("ClassRoomRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClassRoomRoomId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SectionId");

                    b.HasDiscriminator().HasValue("ClassSession");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Conference", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Events.Event");

                    b.Property<Guid?>("SpeakerPersonId")
                        .HasColumnType("uuid");

                    b.HasIndex("SpeakerPersonId");

                    b.HasDiscriminator().HasValue("Conference");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.OfficeHours", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Events.Event");

                    b.Property<bool?>("IsDropIn")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.ToTable("Events", t =>
                        {
                            t.Property("ScheduleId")
                                .HasColumnName("OfficeHours_ScheduleId");
                        });

                    b.HasDiscriminator().HasValue("OfficeHours");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.OfficeMeeting", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Events.Event");

                    b.Property<Guid>("TeacherPersonId")
                        .HasColumnType("uuid");

                    b.HasIndex("TeacherPersonId");

                    b.HasDiscriminator().HasValue("OfficeMeeting");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Admin", b =>
                {
                    b.HasBaseType("DawsonDial.Models.People.Person");

                    b.Property<int>("CreatedUsersCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Student", b =>
                {
                    b.HasBaseType("DawsonDial.Models.People.Person");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Teacher", b =>
                {
                    b.HasBaseType("DawsonDial.Models.People.Person");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OfficeRoomRoomId")
                        .HasColumnType("uuid");

                    b.HasIndex("CourseId");

                    b.HasIndex("OfficeRoomRoomId");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.ClassRoom", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Rooms.Room");

                    b.Property<bool>("HasComputers")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("boolean");

                    b.ToTable("Rooms", t =>
                        {
                            t.Property("HasProjector")
                                .HasColumnName("ClassRoom_HasProjector");
                        });

                    b.HasDiscriminator().HasValue("ClassRoom");
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.ConferenceRoom", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Rooms.Room");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("ConferenceRoom");
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.Office", b =>
                {
                    b.HasBaseType("DawsonDial.Models.Rooms.Room");

                    b.Property<bool>("Shared")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Office");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Event", b =>
                {
                    b.HasOne("DawsonDial.Models.Rooms.ConferenceRoom", null)
                        .WithMany("ScheduledEvents")
                        .HasForeignKey("ConferenceRoomRoomId");

                    b.HasOne("DawsonDial.Models.Rooms.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Section", b =>
                {
                    b.HasOne("DawsonDial.Models.Events.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.Events.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.People.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherPersonId");

                    b.Navigation("Course");

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.SectionRoom", b =>
                {
                    b.HasOne("DawsonDial.Models.Rooms.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.Events.Section", "Section")
                        .WithMany("Rooms")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.TimeSlot", b =>
                {
                    b.HasOne("DawsonDial.Models.Events.Schedule", "Schedule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DawsonDial.Models.People.AdminLog", b =>
                {
                    b.HasOne("DawsonDial.Models.People.Admin", "Admin")
                        .WithMany("Logs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("EventPerson", b =>
                {
                    b.HasOne("DawsonDial.Models.Events.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.People.Person", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SectionStudent", b =>
                {
                    b.HasOne("DawsonDial.Models.Events.Section", null)
                        .WithMany()
                        .HasForeignKey("ClassesSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.People.Student", null)
                        .WithMany()
                        .HasForeignKey("EnrolledStudentsPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DawsonDial.Models.Events.ClassSession", b =>
                {
                    b.HasOne("DawsonDial.Models.Rooms.ClassRoom", null)
                        .WithMany("AssignedClasses")
                        .HasForeignKey("ClassRoomRoomId");

                    b.HasOne("DawsonDial.Models.Events.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.Events.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.Events.Section", null)
                        .WithMany("ClassSessions")
                        .HasForeignKey("SectionId");

                    b.Navigation("Course");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Conference", b =>
                {
                    b.HasOne("DawsonDial.Models.People.Person", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerPersonId");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.OfficeHours", b =>
                {
                    b.HasOne("DawsonDial.Models.Events.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DawsonDial.Models.People.Teacher", "Teacher")
                        .WithOne("OfficeHours")
                        .HasForeignKey("DawsonDial.Models.Events.OfficeHours", "TeacherId");

                    b.Navigation("Schedule");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.OfficeMeeting", b =>
                {
                    b.HasOne("DawsonDial.Models.People.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Teacher", b =>
                {
                    b.HasOne("DawsonDial.Models.Events.Course", null)
                        .WithMany("Teachers")
                        .HasForeignKey("CourseId");

                    b.HasOne("DawsonDial.Models.Rooms.Office", "OfficeRoom")
                        .WithMany("AssignedTeachers")
                        .HasForeignKey("OfficeRoomRoomId");

                    b.Navigation("OfficeRoom");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Course", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Schedule", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("DawsonDial.Models.Events.Section", b =>
                {
                    b.Navigation("ClassSessions");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Admin", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("DawsonDial.Models.People.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("OfficeHours");
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.ClassRoom", b =>
                {
                    b.Navigation("AssignedClasses");
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.ConferenceRoom", b =>
                {
                    b.Navigation("ScheduledEvents");
                });

            modelBuilder.Entity("DawsonDial.Models.Rooms.Office", b =>
                {
                    b.Navigation("AssignedTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
